name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set CREDENTIALS_JSON environment variable
        run: echo "CREDENTIALS_JSON=${{ secrets.CREDENTIALS_JSON }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Copy the JAR file
        run: cp build/libs/TvViewAPI-0.0.1-SNAPSHOT.jar app.jar

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t robinblondin/tvviewapi:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push robinblondin/tvviewapi:latest

      - name: Remove credentials.json
        run: rm -f credentials.json

      - name: Trigger VPS deploy hook
        run: |
          curl -X POST https://tvview.wassblondin.se/deploy \
            -H "Authorization: Bearer ${{ secrets.VPS_WEBHOOK_TOKEN }}"
